# This is a actionlint workflow to lint the Action

name: Lint GitHub Actions workflows
on: [push, pull_request]

jobs:
  actionlint:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Download actionlint
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
        shell: bash
      - name: Check workflow files
        run: ./actionlint

  docker-build-test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
#      -
#        name: Login to DockerHub
#        uses: docker/login-action@v1 
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
#        name: Build and push
        name: Build and test
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
#          push: true
          push: false
          tags: user/app:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      -
#        name: Checkout
#        uses: actions/checkout@v2
#      -
#        name: Validate
#        uses: docker/bake-action@v1
#        with:
#          targets: validate
#      -
#        name: Test
#        uses: docker/bake-action@v1
#        with:
#          targets: test
#      -
#        name: Upload coverage
#        uses: codecov/codecov-action@v1
        #with:
        #  file: ./coverage/clover.xml
